{% set version = "0.2.0" %}

package:
  name: echopype
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/echopype/echopype-{{ version }}.tar.gz
  sha256: 584b36bca072350c2214e3fcf08222b8e23e22e026bb573048a2d2a7a1ca7f65

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - scipy
    - matplotlib-base
    - netcdf4
    - xarray
    - pytz
    - pynmea2
    - click
    - arlpy
    - sphinx-automodapi
    - numpydoc

test:
  imports:
    - echopype

about:
  home: https://github.com/OSOceanAcoustics/echopype
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enhancing interoperability and scalability in analyzing water column sonar data.
  doc_url: https://echopype.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopype

extra:
  recipe-maintainers:
    - lsetiawan
    - leewujung
