{% set version = "0.10.0" %}

package:
  name: echopype
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/echopype/echopype-{{ version }}.tar.gz
  sha256: f23bda230640cf119c7a908d6c4f40939c5320a66072a48d7f653818ccb1c355

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=3.4
  run:
    - python >={{ python_min }},<3.13
    - matplotlib-base
    - bottleneck
    - dask
    - dask-image
    - flox >=0.7.2,<1.0.0
    - jinja2
    - netCDF4 >1.6,<1.7.1
    - numpy <2
    - pandas
    - pynmea2
    - pytz
    - scipy <1.15.2
    - xarray >=2024.11.0
    - zarr >=2,<3
    - fsspec
    - s3fs
    - requests
    - aiohttp
    - cmocean
    - psutil >=5.9.1
    - geopy
    - typing-extensions

test:
  imports:
    - echopype
  commands:
    - pip check
    - python -c "import echopype; assert echopype.__version__ != '0.0.0'"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OSOceanAcoustics/echopype
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enhancing interoperability and scalability in analyzing water column sonar data.
  doc_url: https://echopype.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopype

extra:
  recipe-maintainers:
    - lsetiawan
    - leewujung
