{% set version = "0.5.6" %}

package:
  name: echopype
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/echopype/echopype-{{ version }}.tar.gz
  sha256: 9acc820d48d455f49a725307828ef88838407c728b35ab025a10271a2c73c119

build:
  number: 1
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=3.4
  run:
    - python >=3.6
    - matplotlib-base
    - cmocean
    - dask
    - netCDF4
    - numpy
    - pandas
    - pynmea2
    - pytz
    - scipy
    - xarray
    - zarr
    - fsspec
    - s3fs ==2021.11.0
    - requests
    - aiohttp
    - typing-extensions ~=3.10

test:
  imports:
    - echopype
  commands:
    - pip check
    - python -c "import echopype; assert echopype.__version__ != '0.0.0'"
  requires:
    - pip

about:
  home: https://github.com/OSOceanAcoustics/echopype
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enhancing interoperability and scalability in analyzing water column sonar data.
  doc_url: https://echopype.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopype

extra:
  recipe-maintainers:
    - lsetiawan
    - leewujung
