{% set version = "0.7.1" %}

package:
  name: echopype
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/echopype/echopype-{{ version }}.tar.gz
  sha256: bfb26a91cb2b8818ecb4d75e15d7280438be4de4e17b7b7c70f4bb8d84d0d2d7

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=45
    - setuptools_scm >=3.4
  run:
    - python >=3.6
    - matplotlib-base
    - dask
    - jinja2
    - netCDF4 <1.6
    - numpy
    - pynmea2
    - pytz
    - scipy
    - xarray ==2022.3.0
    - zarr
    - fsspec
    - s3fs
    - requests
    - aiohttp
    - xarray-datatree ==0.0.6
    - cmocean
    - psutil ==5.9.1
    - more-itertools ==8.13.0
    - geopy

test:
  imports:
    - echopype
  commands:
    - pip check
    - python -c "import echopype; assert echopype.__version__ != '0.0.0'"
  requires:
    - pip

about:
  home: https://github.com/OSOceanAcoustics/echopype
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enhancing interoperability and scalability in analyzing water column sonar data.
  doc_url: https://echopype.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopype

extra:
  recipe-maintainers:
    - lsetiawan
    - leewujung
