{% set version = "0.3.1" %}

package:
  name: echopype
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/echopype/echopype-{{ version }}.tar.gz
  sha256: 94549f9497ecde61cc51f54afebe9c859f547a0d2dfa4588daaecdcb89510a1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - click
    - numpy
    - pandas
    - scipy
    - matplotlib
    - netCDF4
    - xarray
    - pytz

test:
  imports:
    - echopype

about:
  home: https://github.com/OSOceanAcoustics/echopype
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Enhancing interoperability and scalability in analyzing water column sonar data.
  doc_url: https://echopype.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopype

extra:
  recipe-maintainers:
    - lsetiawan
    - leewujung
