{% set version = "0.9.1" %}

package:
  name: echopype
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/echopype/echopype-{{ version }}.tar.gz
  sha256: 8cff928f93ca20137affa4ee9c2c8ab9853eeacd91b2dbbb30757765f02cc973

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.9,<3.12
    - setuptools >=45
    - setuptools_scm >=3.4
  run:
    - python >=3.9,<3.12
    - matplotlib-base
    - bottleneck
    - dask
    - dask-image
    - flox >=0.7.2,<1.0.0
    - jinja2
    - netCDF4 >1.6
    - numpy <2
    - pandas
    - pynmea2
    - pytz
    - scipy
    - xarray
    - zarr
    - fsspec
    - s3fs
    - requests
    - aiohttp
    - xarray-datatree ==0.0.6
    - cmocean
    - psutil >=5.9.1
    - geopy

test:
  imports:
    - echopype
  commands:
    - pip check
    - python -c "import echopype; assert echopype.__version__ != '0.0.0'"
  requires:
    - pip

about:
  home: https://github.com/OSOceanAcoustics/echopype
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enhancing interoperability and scalability in analyzing water column sonar data.
  doc_url: https://echopype.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopype

extra:
  recipe-maintainers:
    - lsetiawan
    - leewujung
